### PR TITLE
Use project-wide properties and new dependency

### PR DESCRIPTION
**Pull request by KarlosQ**
* Support for gradle 3.+
* Support for RN 0.56.+

### CODE REVIEW

**Comment by todorone** [comment]
@Sunhat Please look if there any blocker to merge this commit, we need it to support latest RN version.

**Comment by Sunhat** [comment]
I've accepted this pull request, although it's been a while since I've used React Native or even React. My understanding is - and please correct me if I'm wrong - that the features in this RN package are now fully available within React Native

**Comment by todorone** [comment]
@Sunhat Thanks for quick reply.

Unfortunately no, there is no built-in to RN ability to figure out full height of screen when bottom soft bar present, so it's still useful in case if there is soft bar present.

It would be super-helpful if You consider making release, thanks for Your help!

**Comment by Sunhat** [comment]
I'll make a release soon in about 7 hours, at work currently

Sorry for the delay - Thanks

**Comment by bradbyte** [comment]
@Sunhat could you push this release out? Currently held up on an Android upgrade for this. Thank you! 🙏

**Comment by Sunhat** [comment]
I said 7 hours. And 18 days later, I'm doing it. Working on this **RIGHT** now

**Comment by Sunhat** [comment]
I've updated the package now, although if I'm not mistaken, it is possible to directly pull the changes from the github repo without a published change on npmjs? Either way, my bad.

I didn't have this project set up on my laptop until now. It was something I was maintaining while at my previous job role. I'll be sure to keep this up-to-date.

**Pull request merged**
