### PR TITLE
Use the other way to get current activity display (Fixed for RN0.29.0)

### PR DESCRIPTION
**Pull request by BelinChung**

### CODE REVIEW

**Comment by beinginorbit** [comment]
Does this basically screw up < 0.29 builds?

**Comment by ivpusic** [comment]
you can always use version which is <0.29 compatible. For people using 0.29+ this is must have

**Comment by sibelius** [comment]
@jaysoo could u please review this PR and also this one https://github.com/jaysoo/react-native-extra-dimensions-android/pull/7

and publish a new version on npm?

**Comment by sirnacnud** [comment]
Can we get this merged in?

**Comment by MattFoley** [comment]
+1

**Comment by itinance** [comment]
+1

**Comment by Sunhat** [comment]
All of this is now in the latest version - Thanks for contributing

**Pull request closed without merging**
